dtypes={
 # 'age_bin_0': 'object',
 # 'age_bin_1': 'object',
 # 'age_bin_2': 'object',
 # 'age_bin_3': 'object',
 # 'age_bin_4': 'object',
 # 'age_bin_5': 'object',
 # 'age_bin_6': 'object',
 # 'age_bin_7': 'object',
 # 'age_bin_8': 'object',
 # 'age_bin_9': 'object',
 'cancel_public_events': 'object',
 'contact_tracing': 'object',
 'country_name': 'object',
 'cumulative_confirmed': 'float32',
 'cumulative_deceased': 'float32',
 'debt_relief': 'object',
 'emergency_investment_in_healthcare': 'float32',
 'facial_coverings': 'object',
 'fiscal_measures': 'float32',
 'gdp_per_capita_usd': 'float32',
 'gdp_usd': 'float32',
 'income_support': 'object',
 'international_support': 'float32',
 'international_travel_controls': 'object',
 'investment_in_vaccines': 'float32',
 'iso_3166_1_alpha_3': 'object',
 'new_confirmed': 'float32',
 'new_deceased': 'float32',
 'openstreetmap_id': 'float32',
 'population_age_00_09': 'float32',
 'population_age_10_19': 'float32',
 'population_age_20_29': 'float32',
 'population_age_30_39': 'float32',
 'population_age_40_49': 'float32',
 'population_age_50_59': 'float32',
 'population_age_60_69': 'float32',
 'population_age_70_79': 'float32',
 'population_age_80_and_older': 'float32',
 'population_female': 'float32',
 'population_male': 'float32',
 'population_rural': 'float32',
 'population_urban': 'float32',
 'public_information_campaigns': 'object',
 'public_transport_closing': 'object',
 'restrictions_on_gatherings': 'object',
 'restrictions_on_internal_movement': 'object',
 'school_closing': 'object',
 'stay_at_home_requirements': 'object',
 'subregion1_code': 'object',
 'subregion1_name': 'object',
 'subregion2_name': 'object',
 'testing_policy': 'object',
 'vaccination_policy': 'object',
 'workplace_closing': 'object'}

columns = dtypes.keys()